package com.example.mlbanalysis.player.dto;

public record PlayerStatsResponse(
        Integer playerId,
        String season,
        String group,
        Integer gamesPlayed,
        Integer plateAppearances,
        Integer atBats,
        Integer runs,
        Integer hits,
        Integer doubles,
        Integer triples,
        Integer homeRuns,
        Integer rbi,
        Integer baseOnBalls,
        Integer intentionalWalks,
        Integer strikeOuts,
        String avg,
        String obp,
        String slg,
        String ops,
        Integer stolenBases,
        Integer caughtStealing,
        String stolenBasePercentage,
        Integer totalBases,
        Integer hitByPitch,
        Integer groundIntoDoublePlay,
        Integer sacBunts,
        Integer sacFlies,
        Integer numberOfPitches,
        String babip,
        Integer groundOuts,
        Integer airOuts
) {
}
